---
title: "ccm_divergence_analysis_clean"
output: html_document
date: "2025-08-18"
---

```{r setup, include=FALSE, fig.width=12, fig.height=6}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(R.matlab)
library(FactoMineR)
library(ggbeeswarm)
library(pals)
library(missMDA)
library(pheatmap)
library(dendsort)
library(ComplexHeatmap)
library(dendextend)
library(RColorBrewer)
library(circlize)
options(scipen = 999999)

# custom color palette where crc colors are a diff shade of ccm colors
custom_ccm_colors <- c("#82817E", "#850699", "#570699", "#FF00A2", "#FF9500", "#36C1FF", "#FA0202", "#FFFB00", "#004CFF", "#00730D", "#00FFBE", "#759909", "#7D4404")
custom_crc_colors <- c("#A3A29F", "#AA5BB5", "#8952B6", "#FF71BB", "#FFB25B", "#84D2FF", "#FF6E4B", "#FFFC6D", "#8F89FF", "#70A566", "#7FFFD0", "#9CB459", "#A47448")

# cleaner enzyme-mediated reaction names
rxn_names <- c('GLUT', 'HK', 'HPI', 'PFK', 'FBP', 'ALDO',
        'TPI', 'GAPDH', '13DPG-phophatase', 'PGK', 'DPGM', 'DPGase',
        'PGAM', 'ENO', 'PYK', 'PDH', 'G6PD', 'PGL',
        '6PGDH', 'RPE', 'RPM', 'TA', 'TK1', 'TK2', 
        'CS', 'CLY', 'IDH1', 'IDH3', 'IDH2', 'AKGD', 
        'SCOAS', 'SDHA', 'SDHC(D)', 'FUM2', 'FUM1', 'MDH2', 
        'MDH1', 'MMALIC', 'succinate-Q reductase', 'cytochrome oxidase', 'NADH-Q reductase', 'ATP synthase', 
        'LDH', 'MCT', 'GLNS', 'GDH2', 'GDH1(3)', 'H2O (m<->c)', 
        'O2 (m<->c)', 'CO2 (m<->c)', 'Pi (m<->c)', 'H (m<->c)', 'MPC', 'NADH (m<->c)', 
        'NH4 (m<->c)', 'H2O (e<->c)', 'O2 (e<->c)', 'CO2 (e<->c)', 'Pi (e<->c)', 'H (e<->c)', 
        'ASCT2', 'NH4 (e<->c)', 'H2O (b<->e)', 'O2 (b<->e)', 'CO2 (b<->e)', 'Pi (b<->e)', 
        'H (b<->e)', 'Lac (b<->e)', 'Glc (b<->e)', 'Gln (b<->e)', 'NH4 (b<->e)', 'ATPase', 
        'biomass_obj', 'GS')
rxn_names <- as.data.frame(rxn_names)

# group reactions by pathway
glycolysis_rxns <- c('GLUT', 'HK', 'HPI', 'PFK', 'FBP', 'ALDO',
        'TPI', 'GAPDH', '13DPG-phophatase', 'PGK', 'DPGM', 'DPGase',
        'PGAM', 'ENO', 'PYK', 'LDH', 'MCT')
tca_rxns <- c('PDH', 'CS', 'CLY', 'IDH1', 'IDH3', 'IDH2', 'AKGD', 
        'SCOAS', 'SDHA', 'SDHC(D)', 'FUM2', 'FUM1', 'MDH2', 
        'MDH1', 'MMALIC', 'succinate-Q reductase', 'cytochrome oxidase', 'NADH-Q reductase', 'ATP synthase', 'ATPase')
ppp_rxns <- c('G6PD', 'PGL', '6PGDH', 'RPE', 'RPM', 'TA', 'TK1', 'TK2')
glutaminolysis_rxns <- c('GS', 'GLNS', 'GDH2', 'GDH1(3)')
transport_exchange_rxns <- c('H2O (m<->c)', 'O2 (m<->c)', 'CO2 (m<->c)', 'Pi (m<->c)', 'H (m<->c)', 'MPC', 'NADH (m<->c)', 
        'NH4 (m<->c)', 'H2O (e<->c)', 'O2 (e<->c)', 'CO2 (e<->c)', 'Pi (e<->c)', 'H (e<->c)', 
        'ASCT2', 'NH4 (e<->c)', 'H2O (b<->e)', 'O2 (b<->e)', 'CO2 (b<->e)', 'Pi (b<->e)', 
        'H (b<->e)', 'Lac (b<->e)', 'Glc (b<->e)', 'Gln (b<->e)', 'NH4 (b<->e)')
biomass_rxns <- c('biomass_obj')

# model names in messy and clean versions - ordered by clustering results
mod_dendrogram_order <- as.data.frame(c("base", "40_41_LDH", "20_41_LDH", "100_11_PGAM", "100_13_PYK", "80_0_HK", "100_12_ENO", 
                          "60_6_GAPDH", "100_0_HK", "100_1_HPI", "100_15_G6PDH", "80_1_HPI", "60_4_ALDO"))
colnames(mod_dendrogram_order) <- "models"
model_labels_dendro <- c("Base Model", "LDH 40%", "LDH 20%", "PGAM 100%", "PYK 100%", "HK 80%", "ENO 100%", "GAPDH 60%", "HK 100%", "HPI 100%", "G6PDH 100%", "HPI 80%", "ALDO 60%")

# make a df with the color palette and model names for consistency across figures
new_color_df <- tibble(model_cond = paste(model_labels_dendro, c(rep("CCM", length(model_labels_dendro)), rep("CRC", length(model_labels_dendro))), sep = "_"),
                       colors = c(custom_ccm_colors, custom_crc_colors)) 
```

# import sampling data
```{r}
rxn_list <- R.matlab::readMat('data/rxn_names_labelled.mat') 

base_samp <- R.matlab::readMat('data/_1.mat')
base_samp <- base_samp$points

base_rxns <- rxn_names %>% filter(!rxn_names %in% c('RPM', 'CLY', 'Gln (b<->e)')) # reactions removed in the base model during sampling

rownames(base_samp) <- base_rxns$rxn_names # this is the labelled sampling data for the base model
base_samp <- as.data.frame(t(base_samp)) 
base_samp$model <- rep('base')

samp_list <- list.files("data/sampling_results") %>% as.data.frame()
colnames(samp_list) <- c('files')
samp_list <- samp_list %>% filter(str_detect(files, pattern = 'samples'))
samp_list$files <- samp_list[c(1, 3:6, 2, 7:nrow(samp_list)), ] #not strictly necessary bc of how im reading in the files

# remove rxn names, transpose, bind together, then make the colnames the reaction names
samp_data <- list()
for (j in 1:length(samp_list$files)){
  samp_data[[j]] <- R.matlab::readMat(paste0('data/sampling_results/', samp_list$files[j]))
  samp_data[[j]] <- samp_data[[j]]$points
  samp_data[[j]] <- as.data.frame(samp_data[[j]])
  samp_data[[j]]$rxn_names <- unlist(rxn_list[["labels"]][[j]])
  samp_data[[j]] <- left_join(rxn_names, samp_data[[j]], by = 'rxn_names')
  samp_data[[j]]$rxn_names <- NULL
  samp_data[[j]] <- as.data.frame(t(samp_data[[j]]))
  samp_data[[j]]$model <- rep(samp_list$files[j])
}

all_samp_data <- bind_rows(samp_data)
colnames(all_samp_data)[1:74] <- rxn_names$rxn_names

all_samp_data <- all_samp_data %>% mutate_all(~replace_na(., 0)) 
all_samp_data <- all_samp_data %>% select_if(~!all(is.na(.)))

full_samp_data <- bind_rows(base_samp, all_samp_data) %>% 
  mutate_all(~replace_na(., 0))

# remove rxn names, transpose, bind together, then make the colnames the reaction names
base_to_write <- R.matlab::readMat('data/_1.mat')
base_to_write <- base_to_write$points
 base_to_write <- as.data.frame(base_to_write) %>%
   mutate('rxn_names' = base_rxns$rxn_names)

  base_to_write <- left_join(rxn_names, base_to_write, by = 'rxn_names')
  base_to_write$rxn_names <- NULL
  base_to_write <- as.data.frame(t(base_to_write)) %>% mutate_all(~replace_na(., 0))

#write_csv(base_to_write, 'data/sampling_results_rp/base_kras_caf.csv', col_names = FALSE)
```

# Supplemental Figure 1, Figure 4
# boxplots of flux sampling data for each reaction, model
```{r}
# filter for columns not in transport_exchange_rxns
samp_data_not_te <- full_samp_data %>% 
  select(colnames(full_samp_data)[!colnames(full_samp_data) %in% transport_exchange_rxns]) %>%
  mutate(model = str_remove(model, pattern = 'kras_caf_'),
         model = str_remove(model, pattern = '_samples_1.mat')) %>%
   mutate(model = ordered(model, levels = mod_dendrogram_order$models),
          condition = "CCM")

# save cleaned samp data as matlab object for use in crc_divergence_analysis to make supplemental figure 1
# save(samp_data_not_te, file = 'ccm_sampling_data.rds')

# loop through all the reactions, marking a separate plot for each
# lyst <- colnames(samp_data_not_te)[1:48]
# 
# rxn_hist_plots <- lapply(lyst, function(i)ggplot(samp_data_not_te) +
#     geom_boxplot(aes(x=.data[[i]], y=model, color=model), alpha=0.5) +
#       geom_vline(aes(xintercept = 0), linetype = 'dashed', color = 'darkgray') +
#    scale_colour_manual(labels= model_labels_dendro, values=new_color_df$colors) +
#      scale_y_discrete(labels = model_labels_dendro) + 
#     ggtitle(paste('Sampling distribution of', i, 'in all models')) +
#        theme_minimal() +
#   theme(legend.position = 'none') +
#     labs(y=" ")
#    ) 

# for(i in 1:48){
 # ggsave(plot = rxn_hist_plots[[i]], file = paste("samp_distribution_plots/",lyst[i],".png",sep=""))
# }

```

# Find the mean of each reaction in each model for clustering
```{r, height=3, width=12}
# find the mean for each reaction (column) within each model (row)
mean_samp_data <- full_samp_data %>%
  mutate(model = str_remove(model, pattern = 'kras_caf_'), 
         model = str_remove(model, pattern = '_samples_1.mat')) %>%
  group_by(model) %>%
  summarise_all(mean) 

mod_hm <- c("HK 100%", "PGAM 100%", "ENO 100%", "PYK 100%", "G6PDH 100%", "HPI 100%", "LDH 20%", "LDH 40%", "ALDO 60%", "GAPDH 60%", "HK 80%", "HPI 80%",   "Base Model") # this is the nice version of mean_samp_data$model

mean_samp_data <- bind_cols(mod_hm, mean_samp_data) %>%
  rename('Model' = `...1`) %>%
  select(-c(model))

mean_samp_data[,73:75] <- NULL # make 0 columns null for later matrix manipulation

rxns_in_order <- as_data_frame(c(glycolysis_rxns, tca_rxns, ppp_rxns, glutaminolysis_rxns, transport_exchange_rxns, biomass_rxns)) %>% 
  filter(value %in% colnames(mean_samp_data)) %>%
  mutate(Subsystem = case_when(value %in% glycolysis_rxns ~ 'Glycolysis',
                               value %in% tca_rxns ~ 'TCA',
                               value %in% ppp_rxns ~ 'PPP',
                               value %in% glutaminolysis_rxns ~ 'Glutaminolysis',
                               value %in% transport_exchange_rxns ~ 'Transport & Exchange',
                               .default = 'Biomass'))


mean_samp_matrix <- mean_samp_data %>%
  column_to_rownames('Model') %>%
  as.matrix()
mean_samp_matrix_ordered <- mean_samp_data[rxns_in_order$value]
rownames(mean_samp_matrix_ordered) <- mean_samp_data$Model

# perform clustering on mean flux columns
mat_cluster_rows <- hclust(dist(mean_samp_matrix_ordered))
sort_hclust <- function(...) as.hclust(dendsort(as.dendrogram(...)))
mat_cluster_rows <- sort_hclust(mat_cluster_rows)

# plot dendrogram for figure 2
as.dendrogram(rev(mat_cluster_rows)) %>%
  plot(main = " CCM", xlab = "", sub = "", 
       ylim = c(-10, 100), 
       ylab = "") %>%
  title(ylab="Height", line=2, cex.lab=1.2)

# annotation data for heatmap
annotation_col <- rxns_in_order %>%
  column_to_rownames("value") %>%
  rename('Pathway' = 'Subsystem')
annotation2 <- annotation_col %>%
  mutate(Pathway = ifelse(Pathway == "Biomass", " ", Pathway))
pathway_split <- annotation2$Pathway

colnames(mean_samp_matrix_ordered)[71] <- "Biomass"

model_annotations <- data.frame(
  Model = ordered(rownames(mean_samp_matrix_ordered), levels = model_labels_dendro)) %>% arrange(Model)
rownames(model_annotations) <- model_annotations$Model

```

# Figure 2 - heatmap with even color breaks
```{r}
# col_fun = colorRamp2(c(-3, 0, 3), c("#703b0a", "#f8ddc1", "#32283a"))
# col_fun(seq(-3, 3, by = 0.01))

bk1 <- c(seq(-3,-0.1,by=0.01),-0.001)
bk2 <- c(0.001,seq(0.1,3,by=0.01))
bk <- c(bk1,bk2)  # combine the break limits for purpose of graphing

my_palette <- c(colorRampPalette(colors = c('#703b0a', '#a9590e', '#e17713', '#f0bb89', '#f8ddc4'))(n = length(bk1)-1),
              "white", "white",
              c(colorRampPalette(colors = c('#dbd2e6', '#b698cd', '#9678ad', '#645073', '#32283a'))(n = length(bk2)-1)))

ccm_even <- ComplexHeatmap::pheatmap(
  t(mean_samp_matrix_ordered),
  color = my_palette,
   name = "Flux",
  annotation_col = model_annotations,
  annotation_colors = list(
    Model = setNames(new_color_df$colors[1:13], model_labels_dendro)
  ),
  breaks = bk,
    annotation_names_col = FALSE,
  cluster_rows = FALSE,
  cluster_cols = rev(mat_cluster_rows),
  fontsize_row = 7,
  fontsize_col = 7,
  row_split = pathway_split,
  row_gap = unit(1.5, "mm"),
  row_title_gp = gpar(fontsize = 7), 
  heatmap_legend_param = list(
    direction = "horizontal",
    title = "Flux"
  )
)

ccm_even

# save the heatmap ccm_even as an object to be imported into crc_divergence_analysis.Rmd to plot together
# saveRDS(ccm_even, file = 'ccm_heatmap_nice.rds')
```

# Figure 3 - boxplots of fluxes through each pathway in each model
# Summed fluxes through pathways in each model
```{r, fig.width=6, fig.height=14}
full_summed <- full_samp_data %>%
 # group_by(model) %>%
  mutate(glycolysis_sum = rowSums(across(all_of(glycolysis_rxns))),
         tca_sum = rowSums(across(all_of(tca_rxns))),
         ppp_sum = rowSums(across(all_of(ppp_rxns))),
         glutaminolysis_sum = rowSums(across(all_of(glutaminolysis_rxns))),
         transport_exchange_sum = rowSums(across(all_of(transport_exchange_rxns))),
         biomass_sum = rowSums(across(all_of(biomass_rxns)))) %>%
  select(model, glycolysis_sum, tca_sum, ppp_sum, glutaminolysis_sum, transport_exchange_sum, biomass_sum) %>%
  pivot_longer(cols = c(glycolysis_sum, tca_sum, ppp_sum, glutaminolysis_sum, transport_exchange_sum, biomass_sum), 
               names_to = 'subsystem', values_to = 'sum_flux') %>%
  mutate(subsystem = str_remove(subsystem, pattern = '_sum')) %>%
  group_by(model, subsystem) %>%
  mutate(mean_sum = mean(sum_flux)) %>%
  mutate(sd_sum = sd(sum_flux)) %>%
  distinct(model, subsystem, mean_sum, sd_sum) %>%
  mutate(model = str_remove(model, pattern = 'kras_caf_')) %>%
  mutate(model = str_remove(model, pattern = '_samples_1.mat')) %>%
  mutate(model = ordered(model, levels = mod_dendrogram_order$model))

base_mean_sum <- full_summed %>%
  filter(model == 'base') %>%
  select(subsystem, mean_sum, subsystem)

full_summed_no_biomass <- full_summed %>%
  filter(subsystem != 'biomass') %>%
  filter(subsystem != 'transport_exchange') %>%
  mutate(subsystem = factor(subsystem, levels = c('glycolysis', 'tca', 'ppp', 'glutaminolysis'))) %>%
  arrange(model, subsystem)

base_mean_sum_no_biomass <- base_mean_sum %>%
  filter(subsystem != 'transport_exchange')  %>%
  filter(subsystem != 'biomass')

# plot the sum flux of each pathway in each model
summed_flux_ccm_plot <- ggplot(full_summed_no_biomass) +
  geom_hline(data = base_mean_sum_no_biomass, aes(yintercept = mean_sum), color='darkgray', linetype='dashed') +
  geom_bar(aes(x=model, y=mean_sum, fill=model), stat='identity', position='dodge') +
  geom_errorbar(aes(x=model, ymin=mean_sum-sd_sum, ymax=mean_sum+sd_sum), width=0.2) +
  scale_fill_manual(labels= model_labels_dendro, values=new_color_df$colors) +
  theme_minimal() +
  theme(
    axis.text.x = element_blank(),
    panel.grid.minor = element_line(linewidth = 0.1), panel.grid.major = element_line(linewidth = 0.25),
    legend.position = "bottom",
    axis.title.y = element_text(size=12, 
                                  #vjust = 2, 
                                  margin = margin(t = 20)),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    plot.title = element_text(hjust = 0.5),
    strip.text.x = element_blank(),
    panel.spacing = unit(3, "lines")) +
  labs(title = "CCM",
       x = ' ',
       y = 'Mean Sum of Fluxes\n',
       fill = "Model") +
  facet_wrap(vars(subsystem), scales = 'free',
             ncol = 1)
summed_flux_ccm_plot
# ggsave("mean_sum_fluxes_ccm_newpal22.pdf", width = 6, height = 14)
```



